#
# Copyright (C) 2026
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for rtp2httpd
LUCI_DEPENDS:=+rtp2httpd
LUCI_PKGARCH:=all

PKG_MAINTAINER:=Stackie Jia <jsq2627@gmail.com>
PKG_LICENSE:=GPL-2.0-or-later

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
