# Copyright (C) 2025
#
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for VSFTPD
LUCI_DEPENDS:=+vsftpd-alt
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-vsftpd

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
