#!/bin/sh

#设置默认主题语言
uci set luci.main.lang=zh_cn
#uci set luci.main.mediaurlbase=/luci-static/alpha
uci commit luci

#设置时区
uci set system.@system[-1].hostname='OpenWrt'
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci -q del system.ntp.server
uci -q add_list system.ntp.server='ntp1.aliyun.com'
uci -q add_list system.ntp.server='ntp.tencent.com'
uci -q add_list system.ntp.server='ntp.ntsc.ac.cn'
uci -q add_list system.ntp.server='cn.pool.ntp.org'
uci commit system

#删除状态页不需显示的
rm -f /www/luci-static/resources/view/status/include/25_storage.js
#rm -f /www/luci-static/resources/view/status/include/20_memory.js
#rm -f /www/luci-static/resources/view/status/include/50_dsl.js
#rm -f /www/luci-static/resources/view/status/include/70_ddns.js
#rm -f /www/luci-static/resources/view/status/include/80_minidlna.js
#rm -f /www/luci-static/resources/view/status/include/80_upnp.js
rm -f /www/luci-static/resources/view/status/include/90_mwan3.js

#删除不需显示的
#rm -f /etc/nginx/uci.conf.template-opkg
#rm -f /etc/config/nginx-opkg

#修改显示固件
#sed -i "s/LuCI openwrt-22.03 branch/LuCI branch/g" /usr/lib/lua/luci/version.lua
sed -i "s/git-.*-\(.*\)/git-\1/g" /usr/lib/lua/luci/version.lua
#sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
#echo "DISTRIB_REVISION='R22.4.1'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='OpenWrt main'" >> /etc/openwrt_release

#设置ipk菜单位置
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
#sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
#sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm
#sed -i 's/\"services\"/\"vpn\"/g'  /usr/lib/lua/luci/controller/vssr.lua
#sed -i 's/\"services\"/\"vpn\"/g'  /usr/lib/lua/luci/controller/bypass.lua
#sed -i 's/\"services\"/\"vpn\"/g'  /usr/lib/lua/luci/controller/shadowsocksr.lua

#镜像源替换

cat <<EOF >> /etc/apk/repositories.d/customfeeds.list

# bauw feeds
https://bauw2.serv00.net/snapshots/targets/x86/64/packages/packages.adb
https://bauw2.serv00.net/snapshots/packages/x86_64/base/packages.adb
https://bauw2.serv00.net/snapshots/packages/x86_64/luci/packages.adb
https://bauw2.serv00.net/snapshots/packages/x86_64/packages/packages.adb
#https://bauw2.serv00.net/snapshots/packages/x86_64/routing/packages.adb
#https://bauw2.serv00.net/snapshots/packages/x86_64/telephony/packages.adb
#https://bauw2.serv00.net/snapshots/packages/x86_64/video/packages.adb

# immortalwrt feeds
#https://downloads.immortalwrt.org/snapshots/targets/x86/64/packages/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/base/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/luci/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/packages/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/routing/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/telephony/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/video/packages.adb
EOF

FILE="/etc/apk/repositories.d/distfeeds.list"

# 注释掉指定的4条源
sed -i 's|^https://downloads.openwrt.org/snapshots/targets/x86/64/packages/packages.adb|#&|' "$FILE"
sed -i 's|^https://downloads.openwrt.org/snapshots/packages/x86_64/base/packages.adb|#&|' "$FILE"
sed -i 's|^https://downloads.openwrt.org/snapshots/packages/x86_64/luci/packages.adb|#&|' "$FILE"
sed -i 's|^https://downloads.openwrt.org/snapshots/packages/x86_64/packages/packages.adb|#&|' "$FILE"

#无线网络相关配置
#sed -i '/option disabled/d' /etc/config/wireless
#sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

#nginx
grep -q "uwsgi_read_timeout" /etc/nginx/conf.d/luci.locations 2>/dev/null || {
	sed -i "s/include uwsgi_params;/include uwsgi_params;\n\t\tuwsgi_read_timeout 300s;/" /etc/nginx/conf.d/luci.locations
	sed -i '/ubus_parallel_req/a\        ubus_script_timeout 600;' /etc/nginx/conf.d/luci.locations
}

sed -i \
	-e "s/client_max_body_size 128M/client_max_body_size 256M/" \
	-e "s/large_client_header_buffers 2 1k/large_client_header_buffers 4 512k/" \
	/etc/nginx/uci.conf.template
grep -q "client_body_buffer_size" /etc/nginx/uci.conf.template ||
	sed -i "/large_client_header_buffers/a\	client_body_buffer_size 128K;" /etc/nginx/uci.conf.template




rm -rf /tmp/luci-*

exit 0

