#!/bin/sh

# zh_cn
uci set luci.main.lang=zh_cn
#uci set luci.main.mediaurlbase=/luci-static/alpha
uci commit luci

# ntp
uci set system.@system[-1].hostname='OpenWrt'
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci -q del system.ntp.server
uci -q add_list system.ntp.server='ntp1.aliyun.com'
uci -q add_list system.ntp.server='ntp.tencent.com'
uci -q add_list system.ntp.server='ntp.ntsc.ac.cn'
uci -q add_list system.ntp.server='cn.pool.ntp.org'
uci commit system

# network
uci delete network.lan.ipaddr
uci add_list network.lan.ipaddr='10.0.0.1/24'
uci commit network

# status rm -f 
rm -f /www/luci-static/resources/view/status/include/25_storage.js
#rm -f /www/luci-static/resources/view/status/include/20_memory.js
#rm -f /www/luci-static/resources/view/status/include/50_dsl.js
#rm -f /www/luci-static/resources/view/status/include/70_ddns.js
#rm -f /www/luci-static/resources/view/status/include/80_minidlna.js
#rm -f /www/luci-static/resources/view/status/include/80_upnp.js
rm -f /www/luci-static/resources/view/status/include/90_mwan3.js

# nginx rm -f 
#rm -f /etc/nginx/uci.conf.template-opkg
#rm -f /etc/config/nginx-opkg

# menu.d/controller
sed -i 's|services/ksmbd|nas/ksmbd|g' /usr/share/luci/menu.d/luci-app-ksmbd.json
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
#sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua

# apk

cat <<EOF >> /etc/apk/repositories.d/customfeeds.list

# bauw feeds
https://bauw2.serv00.net/snapshots/targets/x86/64/packages/packages.adb
https://bauw2.serv00.net/snapshots/packages/x86_64/base/packages.adb
https://bauw2.serv00.net/snapshots/packages/x86_64/luci/packages.adb
https://bauw2.serv00.net/snapshots/packages/x86_64/packages/packages.adb
#https://bauw2.serv00.net/snapshots/packages/x86_64/routing/packages.adb
#https://bauw2.serv00.net/snapshots/packages/x86_64/telephony/packages.adb
#https://bauw2.serv00.net/snapshots/packages/x86_64/video/packages.adb

# immortalwrt feeds
#https://downloads.immortalwrt.org/snapshots/targets/x86/64/packages/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/base/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/luci/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/packages/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/routing/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/telephony/packages.adb
#https://downloads.immortalwrt.org/snapshots/packages/x86_64/video/packages.adb
EOF

sed -i 's|^https://downloads.openwrt.org/snapshots/targets/x86/64/packages/packages.adb|#&|' /etc/apk/repositories.d/distfeeds.list
sed -i 's|^https://downloads.openwrt.org/snapshots/packages/x86_64/base/packages.adb|#&|' /etc/apk/repositories.d/distfeeds.list
sed -i 's|^https://downloads.openwrt.org/snapshots/packages/x86_64/luci/packages.adb|#&|' /etc/apk/repositories.d/distfeeds.list
sed -i 's|^https://downloads.openwrt.org/snapshots/packages/x86_64/packages/packages.adb|#&|' /etc/apk/repositories.d/distfeeds.list

# wireless
#sed -i '/option disabled/d' /etc/config/wireless
#sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

# nginx
grep -q "uwsgi_read_timeout" /etc/nginx/conf.d/luci.locations 2>/dev/null || {
	sed -i "s/include uwsgi_params;/include uwsgi_params;\n\t\tuwsgi_read_timeout 300s;/" /etc/nginx/conf.d/luci.locations
	sed -i '/ubus_parallel_req/a\        ubus_script_timeout 600;' /etc/nginx/conf.d/luci.locations
}

sed -i \
	-e "s/client_max_body_size 128M/client_max_body_size 256M/" \
	-e "s/large_client_header_buffers 2 1k/large_client_header_buffers 4 512k/" \
	/etc/nginx/uci.conf.template
grep -q "client_body_buffer_size" /etc/nginx/uci.conf.template ||
	sed -i "/large_client_header_buffers/a\	client_body_buffer_size 128K;" /etc/nginx/uci.conf.template

# ttyd
[ -n "$(uci show ttyd 2>/dev/null)" ] && {
	uci set ttyd.@ttyd[0].ssl='1'
	uci set ttyd.@ttyd[0].ssl_cert='/etc/nginx/conf.d/_lan.crt'
	uci set ttyd.@ttyd[0].ssl_key='/etc/nginx/conf.d/_lan.key'
	uci commit ttyd
}

# dhcp.@dnsmasq[0] 节点
uci -q get dhcp.@dnsmasq[0] >/dev/null || uci add dhcp dnsmasq >/dev/null

if ! uci -q get dhcp.@dnsmasq[0].port >/dev/null 2>&1; then
    uci set dhcp.@dnsmasq[0].port='53'
    uci commit dhcp
fi

rm -rf /tmp/luci-*

exit 0

